name: tk-debug

on:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v3
      
      - name: Install python and tk
        shell: bash -l {0}
        run: C:\\Users\\runneradmin\\micromamba-bin\\micromamba.exe create -y -r C:\\Users\\runneradmin\\micromamba -n test_env python=3.14 tk=9.0.4 --log-level debug --rc-file D:\\a\\_temp\\setup-micromamba\\.condarc

      - name: List installed package versions (conda)
        shell: bash -l {0}  # necessary for conda env to be active
        run: micromamba list
